### ISSUE TITLE
Need help in executing the code

### ISSUE THREAD

**Issue by anilkumars-macrolytics** [agalex1974/ProToolkitLExtrusion#2]
Hello, 
First of all, thanks to wonder ful code written by you..!!
When i set up and try to run the creo toolkit solution, I get the below error. Even in the readme document, it does not mention any thing about it. 
Could you please help me out..!!
![image](https://github.com/user-attachments/assets/299e7cbd-55a4-4ff5-87c4-48cf4dbdad3c)

**Comment by agalex1974** [comment]
Hi. Thank you for your kind words. Yes, I can help you out. You need to build a DLL not an exe file and run it on Creo Parametric. I will update the README until Monday.

**Comment by anilkumars-macrolytics** [comment]
Hello,
I built a dll. Now, in creo, it is throwing error.

![image](https://github.com/user-attachments/assets/5d7e4591-7d76-4825-981d-4d887914bb83)

My protk.dat file is updated with the proper path of the dll as well.

**Comment by agalex1974** [comment]
Please do a pull first. I have updated so that it doesn't crash when it can't write the log file and build again.
![image](https://github.com/user-attachments/assets/0e1e190e-3688-4540-94f0-fcd5c7c5a536)
Put the text directory and the dat file in x64/Release change the directory in dat to the full path where the dat is and it will run.

**Comment by anilkumars-macrolytics** [comment]
hello,
I dont think its the issue with fopen() API.. I think the entry point for dll to get attached to Creo, is not working. 
When I put the break point at user_initialize API, it is not hitting the break point itself. This should have been the starting point.

I wonder how it is working at your end !! can you zip me your local project folder from your computer..?

![image](https://github.com/user-attachments/assets/786f741b-3718-4bb8-8038-9432b2e897e2)

![image](https://github.com/user-attachments/assets/f09f4d9d-3bad-44f3-b262-3cee8e7d1b7b)

![image](https://github.com/user-attachments/assets/57702ee0-9007-469c-ad2e-874ee28e6183)

**Comment by agalex1974** [comment]
Before sending you the project can you please try the release configuration as I suggest in ReadMe?

**Comment by anilkumars-macrolytics** [comment]
yeah sure.. !! will update in a min..!!

**Comment by anilkumars-macrolytics** [comment]
Awesome..!! Works in Release Mode..!!! I wonder why it would not work in Debug Mode..

**Comment by anilkumars-macrolytics** [comment]
Ok.. Found the issue that was causing not to load the dll's... it was protoolkit_NU.lib; that was included and below libraries were missing..  

libcmt.lib;gdi32.lib;shell32.lib;comdlg32.lib;ole32.lib;advapi32.lib;winspool.lib.. 

Now, I'm able to run in debug mode as well.. Thks a lot for the support.. !!

Not sure, why addition of protoolkit_NU.lib causes this issue..!!

**Comment by agalex1974** [comment]
Glad to hear everything is working. Have fun with it.

**Comment by anilkumars-macrolytics** [comment]
I'm working on a Project in Creo, for College... Is that ok, if I ask some guidance from you..? If yes, we can connect offline.. please let me know.. I can share my email id..

**Comment by agalex1974** [comment]
ask me in alexander.agathos@gmail.com
I have a very busy work schedule I will try to answer but I can't get involved in the project I can only offer general advices.

**Comment by anilkumars-macrolytics** [comment]
Perfect..!! Thanks a lot.. !! Advice and Guidance is what I need..!! I will take care of implementation..!!

**Comment by anilkumars-macrolytics** [comment]
Issue is resolved.. !! I'm able to run the code in Creo Parametric. Thanks to the author for the wonderful support..!!
